apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: stonesoup-spring-boot-ovzq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: stonesoup-spring-boot-ovzq
    app.kubernetes.io/part-of: spring-boot-2
  name: stonesoup-spring-boot-ovzq
  namespace: oandriie-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: stonesoup-spring-boot-ovzq
    weight: null
status: {}
