apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: stonesoup-spring-boot-ovzq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: stonesoup-spring-boot-ovzq
    app.kubernetes.io/part-of: spring-boot-2
  name: stonesoup-spring-boot-ovzq
  namespace: oandriie-tenant
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: stonesoup-spring-boot-ovzq
status:
  loadBalancer: {}
